// Builds every drawing in drawings/ at both widths, plus the shared stylesheet and a contact
// sheet. Build-time only: nothing here ships to the page except the SVG strings it writes.
//
//   node tools/illustrations/build.mjs [--deps <dir whose node_modules has perfect-freehand, svgo>]
//
// out/<name>-wide.svg, out/<name>-narrow.svg   standalone files (carry their own <style>)
// out/drawings.json                            { name: { title, desc, caption, accent, wide, narrow, plate } }
//                                              inline strings, no <style>: the page loads
// out/illustrations.css                        once per page
// out/sheet.html                               every drawing at both widths on the ground
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { figure, stylesheet, useFreehand, warnings } from './kit.mjs'
import { WIDTH } from './rules.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(HERE, 'out')
fs.mkdirSync(OUT, { recursive: true })

const i = process.argv.indexOf('--deps')
const req = createRequire(i > 0 ? path.resolve(process.argv[i + 1]) + '/node_modules/' : HERE + '/node_modules/')
const tryReq = (m) => { try { return req(m) } catch { return null } }
const pf = tryReq('perfect-freehand')
if (pf) useFreehand(pf.getStroke)
else console.warn('perfect-freehand not found: hand marks fall back to plain strokes (npm i, or pass --deps)')
const svgo = tryReq('svgo')
if (!svgo) console.warn('svgo not found: writing unoptimised SVG')
const optimise = (s) =>
  svgo
    ? svgo.optimize(s, {
        multipass: true,
        plugins: [{ name: 'preset-default', params: { overrides: { cleanupIds: false, inlineStyles: false, minifyStyles: false, removeUnknownsAndDefaults: false, convertShapeToPath: false } } }],
      }).data
    : s

const files = fs.readdirSync(path.join(HERE, 'drawings')).filter((f) => f.endsWith('.mjs')).sort()
const out = {}
for (const file of files) {
  const d = (await import(pathToFileURL(path.join(HERE, 'drawings', file)))).default
  const entry = { title: d.title, desc: d.desc, caption: d.caption, accent: d.accent, sample: !!d.sample }
  for (const v of ['wide', 'narrow']) {
    const before = warnings.length
    const { height, body } = d[v]()
    const opts = { id: `${d.name}-${v}`, width: WIDTH[v], height, accent: d.accent, title: d.title, desc: d.desc, body }
    entry[v] = optimise(figure(opts))
    fs.writeFileSync(path.join(OUT, `${d.name}-${v}.svg`), optimise(figure({ ...opts, standalone: true })) + '\n')
    warnings.slice(before).forEach((w) => console.warn(`  ${d.name}/${v}: ${w}`))
  }
  if (d.plate) {
    const { width, height, body } = d.plate()
    entry.plate = optimise(figure({ id: `${d.name}-plate`, width, height, accent: d.accent, body, plate: true }))
  }
  out[d.name] = entry
  console.log(d.name.padEnd(16), ['wide', 'narrow', 'plate'].filter((v) => entry[v]).map((v) => `${v} ${entry[v].length}B`).join('  '))
}
fs.writeFileSync(path.join(OUT, 'drawings.json'), JSON.stringify(out, null, 2) + '\n')
fs.writeFileSync(path.join(OUT, 'illustrations.css'), '/* Generated by tools/illustrations/build.mjs. Load once per page that has a figure. */\n' + stylesheet() + '\n')

// Contact sheet: both widths side by side on the page ground, captions as the page sets them.
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
const rows = Object.entries(out).map(([n, e]) => `<section><h2>${esc(e.title)}${e.sample ? ' <small>sample</small>' : ''}</h2>
<div class="pair"><figure>${e.wide}<figcaption>${esc(e.caption)}</figcaption></figure><figure class="n">${e.narrow}</figure>${e.plate ? `<figure class="p">${e.plate}</figure>` : ''}</div></section>`).join('\n')
fs.writeFileSync(path.join(OUT, 'sheet.html'), `<!doctype html><meta charset="utf-8"><title>Illustration kit</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,400..600&family=Newsreader:opsz,wght@6..72,400..500&display=swap">
<style>:root{color-scheme:dark;--ground:#0a0a0b;--ink:#e9e5de;--ink-2:#b6b1a8;--ink-3:#8c877f;--ink-4:#5f5b55;--rule-2:rgba(233,229,222,.18);--wash:rgba(233,229,222,.06);--f-ui:Inter,system-ui,sans-serif}
body{margin:0;padding:48px;background:var(--ground);color:var(--ink);font:400 15px/1.45 var(--f-ui)}
h1{font:400 40px/1 Newsreader,serif;margin:0 0 40px}h2{font:400 25px/1.2 Newsreader,serif;margin:0 0 20px}small{font:12px var(--f-ui);color:var(--ink-3);border:1px dashed var(--ink-4);padding:2px 6px;border-radius:4px}
section{padding:32px 0 48px;border-top:1px solid var(--rule-2)}.pair{display:flex;gap:56px;align-items:flex-start;flex-wrap:wrap}
figure{margin:0}figcaption{margin-top:14px;max-width:46em;font-size:13px;color:var(--ink-3)}.p{padding:8px;outline:1px dashed var(--ink-4)}
${stylesheet()}</style><h1>Illustration kit</h1>${rows}\n`)
console.log(warnings.length ? `${warnings.length} warning(s)` : 'no warnings', '→', path.relative(process.cwd(), OUT))
