"""Builds the shared studio HDRI from rig.json and embeds it (and the rig values) in rig.js.

Run with any Python 3 that has numpy (the bpy venv does):
    python tools/objects/make_env.py

Outputs:
  tools/objects/studio.hdr                 Radiance RGBE (RLE), read by Cycles via common.py
  prototypes/e-dark/objects/rig.js         the block between RIG:BEGIN and RIG:END is rewritten

The map is in three.js equirect convention (u = atan2(z, x) / 2pi + 0.5, v = 0.5 + asin(y) / pi,
first row of the file = top). Blender's world lookup of the exported axes lands on the same
directions (checked with calib.py's chrome ball), so common.py uses it unrotated.
"""
import base64
import json
import math
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
RIG_JS = os.path.join(REPO, "prototypes", "e-dark", "objects", "rig.js")


def srgb_to_linear(hex_color):
    h = hex_color.lstrip("#")
    c = np.array([int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)])
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def smooth_edge(x, edge, soft):
    """1 inside |x| < edge, 0 outside, with a smoothstep of width `soft` (degrees)."""
    t = np.clip((edge + soft * 0.5 - np.abs(x)) / soft, 0, 1)
    return t * t * (3 - 2 * t)


def build(env):
    w, h = env["width"], env["height"]
    # pixel centres; row 0 is the top of the image (+y)
    u = (np.arange(w) + 0.5) / w
    v = 1 - (np.arange(h) + 0.5) / h
    uu, vv = np.meshgrid(u, v)
    phi = (uu - 0.5) * 2 * math.pi
    el = (vv - 0.5) * math.pi
    d = np.stack([np.cos(phi) * np.cos(el), np.sin(el), np.sin(phi) * np.cos(el)], -1)

    b = env["base"]
    y = d[..., 1]
    up = np.clip(y, 0, 1) ** 0.6
    dn = np.clip(-y, 0, 1) ** 0.5
    base = b["horizon"] + (b["top"] - b["horizon"]) * up + (b["bottom"] - b["horizon"]) * dn
    img = np.repeat(base[..., None], 3, -1)

    for box in env["boxes"]:
        c = np.array(box["dir"], float)
        c /= np.linalg.norm(c)
        ref = np.array([0.0, 1.0, 0.0]) if abs(c[1]) < 0.9 else np.array([0.0, 0.0, -1.0])
        r = np.cross(ref, c)
        r /= np.linalg.norm(r)
        uvec = np.cross(c, r)
        dc = d @ c
        a = np.degrees(np.arctan2(d @ r, dc))
        bb = np.degrees(np.arctan2(d @ uvec, dc))
        m = smooth_edge(a, box["w"] / 2, env["soft"]) * smooth_edge(bb, box["h"] / 2, env["soft"])
        m = m * (dc > 0)
        img += m[..., None] * box["intensity"] * srgb_to_linear(box["color"])
    return img.astype(np.float32)


def to_rgbe(img):
    m = img.max(-1)
    mant, exp = np.frexp(m)
    scale = np.where(m > 1e-32, mant * 256.0 / np.maximum(m, 1e-32), 0)
    rgb = np.clip(img * scale[..., None], 0, 255).astype(np.uint8)
    e = np.where(m > 1e-32, exp + 128, 0).astype(np.uint8)
    return np.concatenate([rgb, e[..., None]], -1)


def rle_channel(data):
    out = bytearray()
    i, n = 0, len(data)
    while i < n:
        run = 1
        while i + run < n and run < 127 and data[i + run] == data[i]:
            run += 1
        if run > 2:
            out += bytes([128 + run, data[i]])
            i += run
            continue
        j = i
        while j < n and j - i < 128:
            if j + 2 < n and data[j] == data[j + 1] == data[j + 2]:
                break
            j += 1
        out += bytes([j - i]) + bytes(data[i:j])
        i = j
    return out


def write_hdr(path, img):
    h, w, _ = img.shape
    rgbe = to_rgbe(img)
    out = bytearray(f"#?RADIANCE\nFORMAT=32-bit_rle_rgbe\n\n-Y {h} +X {w}\n".encode())
    for row in rgbe:
        out += bytes([2, 2, w >> 8, w & 255])
        for ch in range(4):
            out += rle_channel(row[:, ch].tobytes())
    with open(path, "wb") as f:
        f.write(out)
    return bytes(out)


def main():
    rig = json.load(open(os.path.join(HERE, "rig.json")))
    img = build(rig["env"])
    data = write_hdr(os.path.join(HERE, "studio.hdr"), img)
    b64 = base64.b64encode(data).decode()
    rig_public = {k: v for k, v in rig.items() if not k.startswith("_")}
    block = (
        "/* RIG:BEGIN (generated by tools/objects/make_env.py from rig.json; do not edit) */\n"
        f"export const RIG = {json.dumps(rig_public, separators=(',', ':'))};\n"
        f"const STUDIO_HDR = '{b64}';\n"
        "/* RIG:END */"
    )
    src = open(RIG_JS).read()
    src, n = re.subn(r"/\* RIG:BEGIN.*?/\* RIG:END \*/", lambda _: block, src, flags=re.S)
    if n != 1:
        raise SystemExit("rig.js has no RIG:BEGIN/RIG:END block")
    open(RIG_JS, "w").write(src)
    print(f"studio.hdr {len(data)} bytes, base64 {len(b64)} chars, peak {img.max():.2f}")


if __name__ == "__main__":
    main()
