# Generated by research on 2026-10-08 as a first test (art direction not final).
# Run: python make_recto.py (needs `pip install bpy`, Python 3.13).
"""Headless Blender: a stylised 'PDF document' object (glass page stack + metal clip).
Run: venv/bin/python blender/make_recto.py <outdir>
Exports GLB and renders a Cycles poster PNG."""
import sys, math, os, time
import bpy, bmesh

out = sys.argv[-1]
os.makedirs(out, exist_ok=True)
t0 = time.time()
bpy.ops.wm.read_factory_settings(use_empty=True)
scn = bpy.context.scene


def mat_glass(name, tint=(0.85, 0.9, 1.0, 1), rough=0.05):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    p = m.node_tree.nodes["Principled BSDF"]
    p.inputs["Base Color"].default_value = tint
    p.inputs["Roughness"].default_value = rough
    p.inputs["Transmission Weight"].default_value = 1.0
    p.inputs["IOR"].default_value = 1.45
    p.inputs["Coat Weight"].default_value = 0.6
    return m


def mat_metal(name, col, rough=0.25):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    p = m.node_tree.nodes["Principled BSDF"]
    p.inputs["Base Color"].default_value = col
    p.inputs["Metallic"].default_value = 1.0
    p.inputs["Roughness"].default_value = rough
    return m


def mat_emit(name, col, strength=4.0):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    p = m.node_tree.nodes["Principled BSDF"]
    p.inputs["Base Color"].default_value = col
    p.inputs["Emission Color"].default_value = col
    p.inputs["Emission Strength"].default_value = strength
    return m


glass = mat_glass("Glass")
frost = mat_glass("Frost", (0.95, 0.96, 1.0, 1), rough=0.35)
gold = mat_metal("Gold", (1.0, 0.72, 0.38, 1), 0.18)
steel = mat_metal("Steel", (0.8, 0.82, 0.86, 1), 0.3)
accent = mat_emit("Accent", (1.0, 0.25, 0.2, 1), 6.0)


def page(name, z, mat, w=1.4, h=1.85, t=0.05, fold=0.32):
    """A page slab with a folded-off top-right corner, bevelled."""
    bm = bmesh.new()
    pts = [(-w/2, -h/2), (w/2, -h/2), (w/2, h/2 - fold), (w/2 - fold, h/2), (-w/2, h/2)]
    verts = [bm.verts.new((x, y, 0)) for x, y in pts]
    f = bm.faces.new(verts)
    r = bmesh.ops.extrude_face_region(bm, geom=[f])
    for v in [e for e in r["geom"] if isinstance(e, bmesh.types.BMVert)]:
        v.co.z += t
    bm.normal_update()
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    ob = bpy.data.objects.new(name, me)
    scn.collection.objects.link(ob)
    ob.location.z = z
    bev = ob.modifiers.new("bev", "BEVEL")
    bev.width = 0.018
    bev.segments = 4
    bev.limit_method = "ANGLE"
    ob.data.materials.append(mat)
    for p in me.polygons:
        p.use_smooth = True
    ob.modifiers.new("wn", "WEIGHTED_NORMAL").keep_sharp = True
    return ob


pages = []
for i in range(3):
    ob = page(f"Page{i}", -i * 0.11, glass if i == 0 else frost)
    ob.rotation_euler.z = math.radians(-4 * i)
    ob.location.x = 0.05 * i
    ob.location.y = -0.04 * i
    pages.append(ob)

# Folded corner flap (gold triangle)
bm = bmesh.new()
w, h, fold = 1.4, 1.85, 0.32
a = bm.verts.new((w/2 - fold, h/2, 0.055))
b = bm.verts.new((w/2, h/2 - fold, 0.055))
c = bm.verts.new((w/2 - fold, h/2 - fold, 0.055))
f = bm.faces.new([a, c, b])
r = bmesh.ops.extrude_face_region(bm, geom=[f])
for v in [e for e in r["geom"] if isinstance(e, bmesh.types.BMVert)]:
    v.co.z += 0.03
me = bpy.data.meshes.new("Flap"); bm.to_mesh(me)
flap = bpy.data.objects.new("Flap", me); scn.collection.objects.link(flap)
flap.data.materials.append(gold)
bv = flap.modifiers.new("bev", "BEVEL"); bv.width = 0.01; bv.segments = 3

# Text lines: rounded bars on the top page
for i, ln in enumerate([0.9, 1.0, 0.75, 1.0, 0.6]):
    bpy.ops.mesh.primitive_cube_add(size=1)
    bar = bpy.context.active_object
    bar.name = f"Line{i}"
    bar.scale = (ln * 0.9, 0.045, 0.012)
    bar.location = (-0.05 - (1 - ln) * 0.45, 0.35 - i * 0.16, 0.065)
    bm_ = bar.modifiers.new("bev", "BEVEL"); bm_.width = 0.02; bm_.segments = 4
    bar.data.materials.append(steel if i else accent)

# Paper clip: a curve with round bevel
cu = bpy.data.curves.new("Clip", "CURVE")
cu.dimensions = "3D"
cu.bevel_depth = 0.022
cu.bevel_resolution = 6
sp = cu.splines.new("POLY")
L = [(0, -0.45), (0, 0.25), (0.16, 0.25), (0.16, -0.55), (-0.08, -0.55), (-0.08, 0.15)]
# smooth it with a bezier instead
cu.splines.remove(sp)
sp = cu.splines.new("BEZIER")
sp.bezier_points.add(len(L) - 1)
for p, (x, y) in zip(sp.bezier_points, L):
    p.co = (x, y, 0)
    p.handle_left_type = p.handle_right_type = "AUTO"
cu.resolution_u = 16
clip = bpy.data.objects.new("Clip", cu)
scn.collection.objects.link(clip)
clip.location = (-0.45, 0.85, 0.02)
clip.rotation_euler = (0, math.radians(8), 0)
clip.data.materials.append(gold)

# Tilt the whole object for a hero angle
root = bpy.data.objects.new("Recto", None)
scn.collection.objects.link(root)
for ob in list(scn.collection.objects):
    if ob is not root:
        ob.parent = root
root.rotation_euler = (math.radians(62), math.radians(-10), math.radians(-18))

# --- Export GLB (modifiers applied, curve meshed) ---
glb = os.path.join(out, "recto.glb")
bpy.ops.export_scene.gltf(filepath=glb, export_format="GLB", export_apply=True,
                          export_yup=True)
t1 = time.time()

# --- Cycles poster render on a black ground with area lights ---
world = bpy.data.worlds.new("W"); scn.world = world
world.use_nodes = True
world.node_tree.nodes["Background"].inputs[0].default_value = (0.004, 0.004, 0.006, 1)
for loc, en, col, sz in [((3, -4, 4), 350, (1, 0.9, 0.85), 3), ((-4, -1, 2), 250, (0.55, 0.65, 1), 4),
                         ((0, 4, 1), 900, (1, 0.5, 0.7), 2)]:
    ld = bpy.data.lights.new("L", "AREA"); ld.energy = en; ld.color = col; ld.size = sz
    lo = bpy.data.objects.new("L", ld); scn.collection.objects.link(lo); lo.location = loc
    tr = lo.constraints.new("TRACK_TO"); tr.target = root
camd = bpy.data.cameras.new("C"); camd.lens = 95
cam = bpy.data.objects.new("C", camd); scn.collection.objects.link(cam)
cam.location = (0, -7.5, 1.2); tc = cam.constraints.new("TRACK_TO"); tc.target = root
scn.camera = cam
scn.render.engine = os.environ.get("ENGINE", "CYCLES")
scn.cycles.device = "CPU"
scn.cycles.samples = int(os.environ.get("SAMPLES", 96))
scn.cycles.use_denoising = True
scn.render.resolution_x = scn.render.resolution_y = int(os.environ.get("RES", 1200))
scn.render.film_transparent = False
scn.view_settings.view_transform = "AgX"
scn.render.filepath = os.path.join(out, os.environ.get("NAME", "recto_cycles.png"))
bpy.ops.render.render(write_still=True)
t2 = time.time()
print(f"TIMING export={t1-t0:.1f}s render={t2-t1:.1f}s")
